import type { Category } from "../types";

export const mockCategories: Category[] = [
  {
    id: "cat-electronics",
    name: { en: "Electronics", ar: "الإلكترونيات" },
    slug: "electronics",
    icon: "Monitor",
    parentId: null,
    children: [
      {
        id: "cat-phones",
        name: { en: "Phones", ar: "الهواتف" },
        slug: "phones",
        icon: "Smartphone",
        parentId: "cat-electronics",
        children: [],
        productCount: 24,
      },
      {
        id: "cat-laptops",
        name: { en: "Laptops", ar: "أجهزة الكمبيوتر المحمولة" },
        slug: "laptops",
        icon: "Laptop",
        parentId: "cat-electronics",
        children: [],
        productCount: 18,
      },
      {
        id: "cat-accessories",
        name: { en: "Accessories", ar: "الإكسسوارات" },
        slug: "accessories",
        icon: "Headphones",
        parentId: "cat-electronics",
        children: [],
        productCount: 42,
      },
    ],
    productCount: 84,
  },
  {
    id: "cat-fashion",
    name: { en: "Fashion", ar: "الموضة" },
    slug: "fashion",
    icon: "Shirt",
    parentId: null,
    children: [
      {
        id: "cat-men",
        name: { en: "Men", ar: "رجالي" },
        slug: "men",
        icon: "User",
        parentId: "cat-fashion",
        children: [],
        productCount: 56,
      },
      {
        id: "cat-women",
        name: { en: "Women", ar: "نسائي" },
        slug: "women",
        icon: "User",
        parentId: "cat-fashion",
        children: [],
        productCount: 68,
      },
      {
        id: "cat-shoes",
        name: { en: "Shoes", ar: "الأحذية" },
        slug: "shoes",
        icon: "Footprints",
        parentId: "cat-fashion",
        children: [],
        productCount: 32,
      },
    ],
    productCount: 156,
  },
  {
    id: "cat-beauty",
    name: { en: "Beauty", ar: "الجمال" },
    slug: "beauty",
    icon: "Sparkles",
    parentId: null,
    children: [],
    productCount: 45,
  },
  {
    id: "cat-home-kitchen",
    name: { en: "Home & Kitchen", ar: "المنزل والمطبخ" },
    slug: "home-kitchen",
    icon: "Home",
    parentId: null,
    children: [],
    productCount: 62,
  },
  {
    id: "cat-grocery",
    name: { en: "Grocery", ar: "البقالة" },
    slug: "grocery",
    icon: "ShoppingBasket",
    parentId: null,
    children: [],
    productCount: 38,
  },
  {
    id: "cat-sports",
    name: { en: "Sports", ar: "الرياضة" },
    slug: "sports",
    icon: "Trophy",
    parentId: null,
    children: [],
    productCount: 28,
  },
  {
    id: "cat-furniture",
    name: { en: "Furniture", ar: "الأثاث" },
    slug: "furniture",
    icon: "Armchair",
    parentId: null,
    children: [],
    productCount: 22,
  },
];
