import type { Product } from "../types";

export const mockProducts: Product[] = [
  {
    id: "prod-1",
    sku: "IPH-15-PRO-MAX",
    name: { en: "iPhone 15 Pro Max 256GB", ar: "آيفون 15 برو ماكس 256 جيجابايت" },
    description: {
      en: "The most powerful iPhone ever. A17 Pro chip, 48MP camera system, titanium design, and all-day battery life. Experience the future of mobile technology.",
      ar: "أقوى آيفون على الإطلاق. شريحة A17 Pro، نظام كاميرا 48 ميجابكسل، تصميم التيتانيوم، وبطارية تدوم طوال اليوم. اختبر مستقبل التكنولوجيا المحمولة.",
    },
    shortDescription: {
      en: "A17 Pro chip · 48MP camera · Titanium design",
      ar: "شريحة A17 Pro · كاميرا 48 ميجابكسل · تصميم التيتانيوم",
    },
    brand: { id: "brand-apple", name: "Apple", slug: "apple", productCount: 24 },
    category: { id: "cat-phones", name: { en: "Phones", ar: "الهواتف" }, slug: "phones", icon: "Smartphone", parentId: "cat-electronics", children: [], productCount: 24 },
    images: [
      { url: "https://picsum.photos/seed/iphone15/600/600", alt: { en: "iPhone 15 Pro Max", ar: "آيفون 15 برو ماكس" }, isPrimary: true },
      { url: "https://picsum.photos/seed/iphone15b/600/600", alt: { en: "iPhone 15 Pro Max Back", ar: "ظهر آيفون 15 برو ماكس" }, isPrimary: false },
    ],
    price: 1199.99,
    originalPrice: 1299.99,
    currency: "USD",
    discount: 8,
    rating: 4.8,
    reviewCount: 2341,
    stock: 45,
    status: "in_stock",
    tags: ["new", "bestseller", "premium"],
    variants: [],
    features: ["A17 Pro Chip", "48MP Camera", "Titanium Design", "USB-C", "Dynamic Island"],
    shipping: { free: true, fast: true, sameDay: false, estimatedDays: "2-3" },
    createdAt: "2025-09-12T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-2",
    sku: "SAMS-S24-ULTRA",
    name: { en: "Samsung Galaxy S24 Ultra", ar: "سامسونج جالاكسي S24 ألترا" },
    description: {
      en: "Galaxy AI is here. The ultimate Galaxy experience with built-in AI, a powerful Snapdragon processor, and the incredible 200MP camera.",
      ar: "جالاكسي AI هنا. تجربة جالاكسي النهائية مع AI مدمج، معالج Snapdragon القوي، وكاميرا 200 ميجابكسل المذهلة.",
    },
    shortDescription: {
      en: "Galaxy AI · 200MP camera · S Pen included",
      ar: "جالاكسي AI · كاميرا 200 ميجابكسل · قلم S Pen",
    },
    brand: { id: "brand-samsung", name: "Samsung", slug: "samsung", productCount: 18 },
    category: { id: "cat-phones", name: { en: "Phones", ar: "الهواتف" }, slug: "phones", icon: "Smartphone", parentId: "cat-electronics", children: [], productCount: 24 },
    images: [
      { url: "https://picsum.photos/seed/s24ultra/600/600", alt: { en: "Galaxy S24 Ultra", ar: "جالاكسي S24 ألترا" }, isPrimary: true },
      { url: "https://picsum.photos/seed/s24ultrab/600/600", alt: { en: "Galaxy S24 Ultra Back", ar: "ظهر جالاكسي S24 ألترا" }, isPrimary: false },
    ],
    price: 1099.99,
    originalPrice: 1199.99,
    currency: "USD",
    discount: 8,
    rating: 4.7,
    reviewCount: 1856,
    stock: 32,
    status: "in_stock",
    tags: ["bestseller", "premium"],
    variants: [],
    features: ["Galaxy AI", "200MP Camera", "S Pen", "Snapdragon 8 Gen 3", "5000mAh Battery"],
    shipping: { free: true, fast: true, sameDay: false, estimatedDays: "2-3" },
    createdAt: "2025-01-17T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-3",
    sku: "MBP-M3-MAX-16",
    name: { en: "MacBook Pro 16\" M3 Max", ar: "ماك بوك برو 16 بوصة M3 ماكس" },
    description: {
      en: "Supercharged by M3 Max chip. Up to 22 hours of battery life. Stunning 16-inch Liquid Retina XDR display. The ultimate pro laptop.",
      ar: "مدعوم بشريحة M3 Max. بطارية تدوم حتى 22 ساعة. شاشة Liquid Retina XDR مذهلة مقاس 16 بوصة. الكمبيوتر المحمول الاحترافي النهائي.",
    },
    shortDescription: {
      en: "M3 Max · 22h battery · Liquid Retina XDR",
      ar: "M3 Max · بطارية 22 ساعة · Liquid Retina XDR",
    },
    brand: { id: "brand-apple", name: "Apple", slug: "apple", productCount: 24 },
    category: { id: "cat-laptops", name: { en: "Laptops", ar: "أجهزة الكمبيوتر المحمولة" }, slug: "laptops", icon: "Laptop", parentId: "cat-electronics", children: [], productCount: 18 },
    images: [
      { url: "https://picsum.photos/seed/macbookpro/600/600", alt: { en: "MacBook Pro 16", ar: "ماك بوك برو 16" }, isPrimary: true },
      { url: "https://picsum.photos/seed/macbookprob/600/600", alt: { en: "MacBook Pro Side", ar: "جانب ماك بوك برو" }, isPrimary: false },
    ],
    price: 2499.99,
    originalPrice: 2699.99,
    currency: "USD",
    discount: 7,
    rating: 4.9,
    reviewCount: 1245,
    stock: 18,
    status: "in_stock",
    tags: ["premium", "bestseller"],
    variants: [],
    features: ["M3 Max Chip", "64GB Unified Memory", "1TB SSD", "16\" Liquid Retina XDR", "22h Battery"],
    shipping: { free: true, fast: true, sameDay: false, estimatedDays: "2-4" },
    createdAt: "2025-10-30T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-4",
    sku: "SONY-WH-1000XM5",
    name: { en: "Sony WH-1000XM5 Wireless Headphones", ar: "سماعات سوني WH-1000XM5 اللاسلكية" },
    description: {
      en: "Industry-leading noise cancellation with Auto NC Optimizer. Crystal clear hands-free calling. 30-hour battery life. Premium comfort.",
      ar: "إلغاء الضوضاء الرائد في الصناعة مع محسن NC التلقائي. مكالمات حر اليدين واضحة تمامًا. بطارية تدوم 30 ساعة. راحة فاخرة.",
    },
    shortDescription: {
      en: "Noise cancelling · 30h battery · Premium sound",
      ar: "إلغاء الضوضاء · بطارية 30 ساعة · صوت فاخر",
    },
    brand: { id: "brand-sony", name: "Sony", slug: "sony", productCount: 12 },
    category: { id: "cat-accessories", name: { en: "Accessories", ar: "الإكسسوارات" }, slug: "accessories", icon: "Headphones", parentId: "cat-electronics", children: [], productCount: 42 },
    images: [
      { url: "https://picsum.photos/seed/sonyxm5/600/600", alt: { en: "Sony WH-1000XM5", ar: "سوني WH-1000XM5" }, isPrimary: true },
      { url: "https://picsum.photos/seed/sonyxm5b/600/600", alt: { en: "Sony Headphones Side", ar: "جانب سماعات سوني" }, isPrimary: false },
    ],
    price: 349.99,
    originalPrice: 399.99,
    currency: "USD",
    discount: 13,
    rating: 4.7,
    reviewCount: 3210,
    stock: 67,
    status: "in_stock",
    tags: ["bestseller", "premium"],
    variants: [],
    features: ["Auto NC Optimizer", "30h Battery", "Multipoint Connection", "Premium Comfort", "Hi-Res Audio"],
    shipping: { free: true, fast: true, sameDay: false, estimatedDays: "1-2" },
    createdAt: "2025-05-20T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-5",
    sku: "NIKE-AIR-MAX-270",
    name: { en: "Nike Air Max 270 React", ar: "نايك اير ماكس 270 رياكت" },
    description: {
      en: "The Nike Air Max 270 React combines the iconic Air Max heel with a lightweight foam midsole for all-day comfort and style.",
      ar: "تجمع نايك اير ماكس 270 رياكت بين كعب Air Max الأيقوني ونعل أوسط من الفوم خفيف الوزن لراحة وأناقة تدوم طوال اليوم.",
    },
    shortDescription: {
      en: "Air Max cushioning · React foam · Iconic style",
      ar: "وسادة Air Max · فوم React · أناقة أيقونية",
    },
    brand: { id: "brand-nike", name: "Nike", slug: "nike", productCount: 32 },
    category: { id: "cat-shoes", name: { en: "Shoes", ar: "الأحذية" }, slug: "shoes", icon: "Footprints", parentId: "cat-fashion", children: [], productCount: 32 },
    images: [
      { url: "https://picsum.photos/seed/nike270/600/600", alt: { en: "Nike Air Max 270", ar: "نايك اير ماكس 270" }, isPrimary: true },
      { url: "https://picsum.photos/seed/nike270b/600/600", alt: { en: "Nike Air Max Side", ar: "جانب نايك اير ماكس" }, isPrimary: false },
    ],
    price: 149.99,
    originalPrice: 179.99,
    currency: "USD",
    discount: 17,
    rating: 4.5,
    reviewCount: 4521,
    stock: 128,
    status: "in_stock",
    tags: ["bestseller", "trending"],
    variants: [],
    features: ["Air Max Heel", "React Foam", "Mesh Upper", "Rubber Outsole", "Padded Collar"],
    shipping: { free: true, fast: false, sameDay: false, estimatedDays: "3-5" },
    createdAt: "2025-03-15T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-6",
    sku: "ADIDAS-ULTRA-4D",
    name: { en: "Adidas Ultraboost 4D", ar: "أديداس ألترابوست 4D" },
    description: {
      en: "Revolutionary 4D-printed midsole technology meets the iconic Ultraboost silhouette. Unmatched energy return and adaptive comfort.",
      ar: "تقنية النعل الأوسط المطبوعة بتقنية 4D الثورية تلتقي مع تصميم Ultraboost الأيقوني. عائد طاقة لا مثيل له وراحة متكيفة.",
    },
    shortDescription: {
      en: "4D printed midsole · Primeknit upper · Energy return",
      ar: "نعل 4D مطبوع · قمة Primeknit · عائد طاقة",
    },
    brand: { id: "brand-adidas", name: "Adidas", slug: "adidas", productCount: 28 },
    category: { id: "cat-shoes", name: { en: "Shoes", ar: "الأحذية" }, slug: "shoes", icon: "Footprints", parentId: "cat-fashion", children: [], productCount: 32 },
    images: [
      { url: "https://picsum.photos/seed/adidas4d/600/600", alt: { en: "Adidas Ultraboost 4D", ar: "أديداس ألترابوست 4D" }, isPrimary: true },
      { url: "https://picsum.photos/seed/adidas4db/600/600", alt: { en: "Adidas Ultraboost Side", ar: "جانب أديداس ألترابوست" }, isPrimary: false },
    ],
    price: 219.99,
    originalPrice: 259.99,
    currency: "USD",
    discount: 15,
    rating: 4.6,
    reviewCount: 1876,
    stock: 54,
    status: "in_stock",
    tags: ["premium", "new"],
    variants: [],
    features: ["4D Midsole", "Primeknit Upper", "Continental Rubber", "Energy Return", "Adaptive Fit"],
    shipping: { free: true, fast: false, sameDay: false, estimatedDays: "3-5" },
    createdAt: "2025-08-01T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-7",
    sku: "LG-OLED-65-C3",
    name: { en: "LG 65\" OLED C3 4K Smart TV", ar: "تلفزيون LG OLED C3 65 بوصة 4K" },
    description: {
      en: "Experience perfect blacks and infinite contrast with LG's self-lit OLED technology. α9 Gen6 AI processor for stunning picture quality.",
      ar: "اختبر اللون الأسود المثالي والتباين اللامتناهي مع تقنية OLED ذاتية الإضاءة من LG. معالج α9 Gen6 AI لجودة صورة مذهلة.",
    },
    shortDescription: {
      en: "OLED display · α9 Gen6 AI · Dolby Vision · 120Hz",
      ar: "شاشة OLED · α9 Gen6 AI · دولبي فيجن · 120 هرتز",
    },
    brand: { id: "brand-lg", name: "LG", slug: "lg", productCount: 15 },
    category: { id: "cat-electronics", name: { en: "Electronics", ar: "الإلكترونيات" }, slug: "electronics", icon: "Monitor", parentId: null, children: [], productCount: 84 },
    images: [
      { url: "https://picsum.photos/seed/lgoled/600/600", alt: { en: "LG OLED TV", ar: "تلفزيون LG OLED" }, isPrimary: true },
      { url: "https://picsum.photos/seed/lgoledb/600/600", alt: { en: "LG OLED Side", ar: "جانب LG OLED" }, isPrimary: false },
    ],
    price: 1499.99,
    originalPrice: 1799.99,
    currency: "USD",
    discount: 17,
    rating: 4.8,
    reviewCount: 892,
    stock: 12,
    status: "in_stock",
    tags: ["premium", "bestseller"],
    variants: [],
    features: ["Self-lit OLED", "α9 Gen6 AI", "Dolby Vision", "120Hz Refresh", "WebOS 23"],
    shipping: { free: true, fast: true, sameDay: true, estimatedDays: "1" },
    createdAt: "2025-04-10T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-8",
    sku: "DELL-XPS-15",
    name: { en: "Dell XPS 15 OLED Laptop", ar: "كمبيوتر ديل XPS 15 OLED المحمول" },
    description: {
      en: "Stunning 15.6-inch 3.5K OLED InfinityEdge display. 13th Gen Intel Core i9. NVIDIA GeForce RTX 4060. The ultimate creative laptop.",
      ar: "شاشة OLED InfinityEdge مقاس 15.6 بوصة بدقة 3.5K مذهلة. معالج Intel Core i9 من الجيل الثالث عشر. NVIDIA GeForce RTX 4060. الكمبيوتر المحمول الإبداعي النهائي.",
    },
    shortDescription: {
      en: "3.5K OLED · i9-13900H · RTX 4060 · 32GB RAM",
      ar: "OLED 3.5K · i9-13900H · RTX 4060 · 32 جيجابايت رام",
    },
    brand: { id: "brand-dell", name: "Dell", slug: "dell", productCount: 10 },
    category: { id: "cat-laptops", name: { en: "Laptops", ar: "أجهزة الكمبيوتر المحمولة" }, slug: "laptops", icon: "Laptop", parentId: "cat-electronics", children: [], productCount: 18 },
    images: [
      { url: "https://picsum.photos/seed/dellxps/600/600", alt: { en: "Dell XPS 15", ar: "ديل XPS 15" }, isPrimary: true },
      { url: "https://picsum.photos/seed/dellxpsb/600/600", alt: { en: "Dell XPS Side", ar: "جانب ديل XPS" }, isPrimary: false },
    ],
    price: 1899.99,
    originalPrice: 2199.99,
    currency: "USD",
    discount: 14,
    rating: 4.6,
    reviewCount: 654,
    stock: 8,
    status: "in_stock",
    tags: ["premium"],
    variants: [],
    features: ["3.5K OLED", "i9-13900H", "RTX 4060", "32GB DDR5", "1TB SSD"],
    shipping: { free: true, fast: true, sameDay: false, estimatedDays: "2-3" },
    createdAt: "2025-06-15T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-9",
    sku: "BOSE-QC-ULTRA",
    name: { en: "Bose QuietComfort Ultra Earbuds", ar: "سماعات بوز QuietComfort Ultra اللاسلكية" },
    description: {
      en: "World-class noise cancellation with CustomTune technology. Immersive audio with Bose Immersive Audio. Up to 6 hours of battery life.",
      ar: "إلغاء ضوضاء عالمي المستوى مع تقنية CustomTune. صوت غامر مع Bose Immersive Audio. بطارية تدوم حتى 6 ساعات.",
    },
    shortDescription: {
      en: "CustomTune NC · Immersive Audio · IPX4",
      ar: "CustomTune NC · صوت غامر · IPX4",
    },
    brand: { id: "brand-bose", name: "Bose", slug: "bose", productCount: 6 },
    category: { id: "cat-accessories", name: { en: "Accessories", ar: "الإكسسوارات" }, slug: "accessories", icon: "Headphones", parentId: "cat-electronics", children: [], productCount: 42 },
    images: [
      { url: "https://picsum.photos/seed/boseqc/600/600", alt: { en: "Bose QC Ultra", ar: "بوز QC Ultra" }, isPrimary: true },
      { url: "https://picsum.photos/seed/boseqcb/600/600", alt: { en: "Bose QC Case", ar: "علبة بوز QC" }, isPrimary: false },
    ],
    price: 299.99,
    originalPrice: 349.99,
    currency: "USD",
    discount: 14,
    rating: 4.5,
    reviewCount: 1432,
    stock: 89,
    status: "in_stock",
    tags: ["bestseller", "premium"],
    variants: [],
    features: ["CustomTune NC", "Bose Immersive Audio", "IPX4", "6h Battery", "Wireless Charging"],
    shipping: { free: true, fast: true, sameDay: false, estimatedDays: "1-2" },
    createdAt: "2025-09-01T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-10",
    sku: "UA-HOVR-PHANTOM-3",
    name: { en: "Under Armour HOVR Phantom 3", ar: "أندر أرمور HOVR فانتوم 3" },
    description: {
      en: "UA HOVR technology provides zero-gravity feel to eliminate impact. Connected to UA MapMyRun. Breathable knit upper for ultimate comfort.",
      ar: "توفر تقنية UA HOVR إحساسًا بانعدام الجاذبية للتخلص من الصدمات. متصل بـ UA MapMyRun. قمة محبوكة قابلة للتنفس لراحة فائقة.",
    },
    shortDescription: {
      en: "Zero-gravity feel · Connected · Breathable knit",
      ar: "إحساس بانعدام الجاذبية · متصل · قمة محبوكة قابلة للتنفس",
    },
    brand: { id: "brand-under-armour", name: "Under Armour", slug: "under-armour", productCount: 14 },
    category: { id: "cat-shoes", name: { en: "Shoes", ar: "الأحذية" }, slug: "shoes", icon: "Footprints", parentId: "cat-fashion", children: [], productCount: 32 },
    images: [
      { url: "https://picsum.photos/seed/uahovr/600/600", alt: { en: "UA HOVR Phantom", ar: "UA HOVR فانتوم" }, isPrimary: true },
      { url: "https://picsum.photos/seed/uahovrb/600/600", alt: { en: "UA HOVR Side", ar: "جانب UA HOVR" }, isPrimary: false },
    ],
    price: 139.99,
    originalPrice: 159.99,
    currency: "USD",
    discount: 13,
    rating: 4.4,
    reviewCount: 987,
    stock: 73,
    status: "in_stock",
    tags: ["trending"],
    variants: [],
    features: ["HOVR Technology", "MapMyRun Connected", "Knit Upper", "Charged Cushioning", "Rubber Outsole"],
    shipping: { free: true, fast: false, sameDay: false, estimatedDays: "3-5" },
    createdAt: "2025-07-20T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-11",
    sku: "SAMS-65-QN90C",
    name: { en: "Samsung 65\" Neo QLED 4K TV", ar: "تلفزيون سامسونج Neo QLED 65 بوصة 4K" },
    description: {
      en: "Neo Quantum HDR+ with Quantum Matrix Technology. Dolby Atmos and Object Tracking Sound+. The ultimate home cinema experience.",
      ar: "Neo Quantum HDR+ مع تقنية Quantum Matrix. Dolby Atmos و Object Tracking Sound+. تجربة السينما المنزلية النهائية.",
    },
    shortDescription: {
      en: "Neo QLED · Quantum HDR+ · Dolby Atmos",
      ar: "Neo QLED · Quantum HDR+ · Dolby Atmos",
    },
    brand: { id: "brand-samsung", name: "Samsung", slug: "samsung", productCount: 18 },
    category: { id: "cat-electronics", name: { en: "Electronics", ar: "الإلكترونيات" }, slug: "electronics", icon: "Monitor", parentId: null, children: [], productCount: 84 },
    images: [
      { url: "https://picsum.photos/seed/samsungtv/600/600", alt: { en: "Samsung Neo QLED", ar: "سامسونج Neo QLED" }, isPrimary: true },
      { url: "https://picsum.photos/seed/samsungtvb/600/600", alt: { en: "Samsung TV Side", ar: "جانب تلفزيون سامسونج" }, isPrimary: false },
    ],
    price: 1299.99,
    originalPrice: 1599.99,
    currency: "USD",
    discount: 19,
    rating: 4.7,
    reviewCount: 743,
    stock: 15,
    status: "in_stock",
    tags: ["premium", "bestseller"],
    variants: [],
    features: ["Neo QLED", "Quantum HDR+", "Dolby Atmos", "120Hz", "Tizen OS"],
    shipping: { free: true, fast: true, sameDay: true, estimatedDays: "1" },
    createdAt: "2025-03-01T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-12",
    sku: "PUMA-RS-X3",
    name: { en: "Puma RS-X3 Sneakers", ar: "حذاء بوما RS-X3 الرياضي" },
    description: {
      en: "Bold, chunky silhouette with RS (Running System) cushioning. Mesh and leather upper for durability and style. A streetwear icon.",
      ar: "تصميم جريء وضخم مع وسادة RS (نظام الجري). قمة من الشبك والجلد للمتانة والأناقة. أيقونة أزياء الشارع.",
    },
    shortDescription: {
      en: "Chunky silhouette · RS cushioning · Streetwear icon",
      ar: "تصميم ضخم · وسادة RS · أيقونة أزياء الشارع",
    },
    brand: { id: "brand-puma", name: "Puma", slug: "puma", productCount: 11 },
    category: { id: "cat-shoes", name: { en: "Shoes", ar: "الأحذية" }, slug: "shoes", icon: "Footprints", parentId: "cat-fashion", children: [], productCount: 32 },
    images: [
      { url: "https://picsum.photos/seed/pumarsx/600/600", alt: { en: "Puma RS-X3", ar: "بوما RS-X3" }, isPrimary: true },
      { url: "https://picsum.photos/seed/pumarsxb/600/600", alt: { en: "Puma RS-X3 Side", ar: "جانب بوما RS-X3" }, isPrimary: false },
    ],
    price: 89.99,
    originalPrice: 119.99,
    currency: "USD",
    discount: 25,
    rating: 4.3,
    reviewCount: 2345,
    stock: 156,
    status: "in_stock",
    tags: ["trending"],
    variants: [],
    features: ["RS Cushioning", "Mesh Upper", "Leather Overlays", "Rubber Sole", "Padded Tongue"],
    shipping: { free: false, fast: false, sameDay: false, estimatedDays: "5-7" },
    createdAt: "2025-02-10T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-13",
    sku: "HP-SPECTRE-X360",
    name: { en: "HP Spectre x360 14\" 2-in-1", ar: "إتش بي سبيكتر x360 14 بوصة 2 في 1" },
    description: {
      en: "Premium 2-in-1 laptop with 3K2K OLED display. Intel Core Ultra 7 processor. AI-powered features. Gem-cut design with precision craftsmanship.",
      ar: "كمبيوتر محمول 2 في 1 فاخر مع شاشة OLED 3K2K. معالج Intel Core Ultra 7. ميزات مدعومة بالذكاء الاصطناعي. تصميم مقطوع الأحجار الكريمة مع حرفية دقيقة.",
    },
    shortDescription: {
      en: "3K2K OLED · Core Ultra 7 · AI-powered · 2-in-1",
      ar: "OLED 3K2K · Core Ultra 7 · مدعوم بالذكاء الاصطناعي · 2 في 1",
    },
    brand: { id: "brand-hp", name: "HP", slug: "hp", productCount: 8 },
    category: { id: "cat-laptops", name: { en: "Laptops", ar: "أجهزة الكمبيوتر المحمولة" }, slug: "laptops", icon: "Laptop", parentId: "cat-electronics", children: [], productCount: 18 },
    images: [
      { url: "https://picsum.photos/seed/hpspectre/600/600", alt: { en: "HP Spectre x360", ar: "إتش بي سبيكتر x360" }, isPrimary: true },
      { url: "https://picsum.photos/seed/hpspectreb/600/600", alt: { en: "HP Spectre Tablet Mode", ar: "وضع الجهاز اللوحي إتش بي سبيكتر" }, isPrimary: false },
    ],
    price: 1599.99,
    originalPrice: 1899.99,
    currency: "USD",
    discount: 16,
    rating: 4.5,
    reviewCount: 432,
    stock: 22,
    status: "in_stock",
    tags: ["premium", "new"],
    variants: [],
    features: ["3K2K OLED", "Core Ultra 7", "16GB RAM", "512GB SSD", "AI Features"],
    shipping: { free: true, fast: true, sameDay: false, estimatedDays: "2-3" },
    createdAt: "2025-11-01T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-14",
    sku: "ZARA-CASHMERE-COAT",
    name: { en: "Zara Premium Cashmere Coat", ar: "معطف كشمير فاخر من زارا" },
    description: {
      en: "Luxurious pure cashmere coat with an oversized fit. Notch lapel, long sleeves, and front button closure. A timeless wardrobe essential.",
      ar: "معطف كشمير نقي فاخر بقصة كبيرة الحجم. ياقة notch، أكمام طويلة، وإغلاق أمامي بأزرار. قطعة أساسية خالدة في خزانة الملابس.",
    },
    shortDescription: {
      en: "Pure cashmere · Oversized fit · Timeless design",
      ar: "كشمير نقي · قصة كبيرة · تصميم خالد",
    },
    brand: { id: "brand-zara", name: "Zara", slug: "zara", productCount: 20 },
    category: { id: "cat-fashion", name: { en: "Fashion", ar: "الموضة" }, slug: "fashion", icon: "Shirt", parentId: null, children: [], productCount: 156 },
    images: [
      { url: "https://picsum.photos/seed/zaracoat/600/600", alt: { en: "Zara Cashmere Coat", ar: "معطف كشمير زارا" }, isPrimary: true },
      { url: "https://picsum.photos/seed/zaracoatb/600/600", alt: { en: "Zara Coat Detail", ar: "تفاصيل معطف زارا" }, isPrimary: false },
    ],
    price: 299.99,
    originalPrice: 399.99,
    currency: "USD",
    discount: 25,
    rating: 4.6,
    reviewCount: 567,
    stock: 34,
    status: "in_stock",
    tags: ["premium", "trending"],
    variants: [],
    features: ["Pure Cashmere", "Oversized Fit", "Notch Lapel", "Button Closure", "Dry Clean Only"],
    shipping: { free: true, fast: false, sameDay: false, estimatedDays: "3-5" },
    createdAt: "2025-10-05T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
  {
    id: "prod-15",
    sku: "APPLE-WATCH-U2",
    name: { en: "Apple Watch Ultra 2", ar: "آبل واتش ألترا 2" },
    description: {
      en: "The most rugged and capable Apple Watch ever. 49mm titanium case, precision dual-frequency GPS, and up to 36 hours of battery life. Built for endurance athletes and explorers.",
      ar: "أقوى وأكثر ساعات Apple Watch قدرة على الإطلاق. هيكل تيتانيوم 49 مم، GPS مزدوج التردد دقيق، وبطارية تدوم حتى 36 ساعة. مصممة لرياضيي التحمل والمستكشفين.",
    },
    shortDescription: {
      en: "49mm titanium · Dual-frequency GPS · 36h battery",
      ar: "تيتانيوم 49 مم · GPS مزدوج التردد · بطارية 36 ساعة",
    },
    brand: { id: "brand-apple", name: "Apple", slug: "apple", productCount: 24 },
    category: { id: "cat-accessories", name: { en: "Accessories", ar: "الإكسسوارات" }, slug: "accessories", icon: "Headphones", parentId: "cat-electronics", children: [], productCount: 42 },
    images: [
      { url: "https://picsum.photos/seed/awu2/600/600", alt: { en: "Apple Watch Ultra 2", ar: "آبل واتش ألترا 2" }, isPrimary: true },
      { url: "https://picsum.photos/seed/awu2b/600/600", alt: { en: "Apple Watch Ultra Side", ar: "جانب آبل واتش ألترا" }, isPrimary: false },
    ],
    price: 799.99,
    originalPrice: 899.99,
    currency: "USD",
    discount: 11,
    rating: 4.7,
    reviewCount: 1876,
    stock: 28,
    status: "in_stock",
    tags: ["premium", "bestseller"],
    variants: [],
    features: ["49mm Titanium", "Dual-frequency GPS", "36h Battery", "Action Button", "100m Water Resistant"],
    shipping: { free: true, fast: true, sameDay: false, estimatedDays: "2-3" },
    createdAt: "2025-09-22T10:00:00Z",
    updatedAt: "2025-12-01T08:00:00Z",
  },
];
