export type Locale = "en" | "ar";

export const translations: Record<Locale, Record<string, string>> = {
  en: {
    "products.title": "Products",
    "products.count": "{count} products found",
    "products.search": "Search products...",
    "products.sort.featured": "Featured",
    "products.sort.best_selling": "Best Selling",
    "products.sort.newest": "Newest",
    "products.sort.price_asc": "Price: Low to High",
    "products.sort.price_desc": "Price: High to Low",
    "products.sort.highest_rated": "Highest Rated",
    "products.grid": "Grid",
    "products.list": "List",
    "products.filters": "Filters",
    "products.clear_all": "Clear All",
    "products.clear_filters": "Clear Filters",
    "products.no_results": "No products found",
    "products.no_results_desc": "Try adjusting your search or filter criteria",
    "products.add_to_cart": "Add to Cart",
    "products.add_to_wishlist": "Add to Wishlist",
    "products.quick_view": "Quick View",
    "products.compare": "Compare",
    "products.in_stock": "In Stock",
    "products.out_of_stock": "Out of Stock",
    "products.preorder": "Preorder",
    "products.free_shipping": "Free Shipping",
    "products.fast_delivery": "Fast Delivery",
    "products.same_day": "Same Day",
    "products.reviews": "{count} reviews",
    "products.discount": "-{discount}%",
    "categories": "Categories",
    "price_range": "Price Range",
    "brands": "Brands",
    "rating": "Rating",
    "availability": "Availability",
    "discounts": "Discounts",
    "shipping": "Shipping",
    "filter.5_stars": "5 Stars",
    "filter.4_plus": "4 Stars & Up",
    "filter.3_plus": "3 Stars & Up",
    "filter.10_plus": "10% or more",
    "filter.20_plus": "20% or more",
    "filter.30_plus": "30% or more",
    "filter.50_plus": "50% or more",
    "filter.in_stock": "In Stock",
    "filter.out_of_stock": "Out of Stock",
    "filter.preorder": "Preorder",
    "filter.free_shipping": "Free Shipping",
    "filter.fast_delivery": "Fast Delivery",
    "filter.same_day": "Same Day Delivery",
    "filter.min": "Min",
    "filter.max": "Max",
    "filter.go": "Go",
    "filter.reset": "Reset",
    "filter.search_brands": "Search brands...",
    "all_categories": "All Categories",
  },
  ar: {
    "products.title": "المنتجات",
    "products.count": "تم العثور على {count} منتج",
    "products.search": "ابحث عن المنتجات...",
    "products.sort.featured": "مميز",
    "products.sort.best_selling": "الأكثر مبيعاً",
    "products.sort.newest": "الأحدث",
    "products.sort.price_asc": "السعر: من الأقل إلى الأعلى",
    "products.sort.price_desc": "السعر: من الأعلى إلى الأقل",
    "products.sort.highest_rated": "الأعلى تقييماً",
    "products.grid": "شبكة",
    "products.list": "قائمة",
    "products.filters": "تصفية",
    "products.clear_all": "مسح الكل",
    "products.clear_filters": "مسح التصفية",
    "products.no_results": "لم يتم العثور على منتجات",
    "products.no_results_desc": "حاول تعديل معايير البحث أو التصفية",
    "products.add_to_cart": "أضف إلى السلة",
    "products.add_to_wishlist": "أضف إلى المفضلة",
    "products.quick_view": "عرض سريع",
    "products.compare": "مقارنة",
    "products.in_stock": "متوفر",
    "products.out_of_stock": "غير متوفر",
    "products.preorder": "طلب مسبق",
    "products.free_shipping": "شحن مجاني",
    "products.fast_delivery": "توصيل سريع",
    "products.same_day": "نفس اليوم",
    "products.reviews": "{count} تقييم",
    "products.discount": "-{discount}%",
    "categories": "التصنيفات",
    "price_range": "نطاق السعر",
    "brands": "الماركات",
    "rating": "التقييم",
    "availability": "التوفر",
    "discounts": "الخصومات",
    "shipping": "الشحن",
    "filter.5_stars": "5 نجوم",
    "filter.4_plus": "4 نجوم فأكثر",
    "filter.3_plus": "3 نجوم فأكثر",
    "filter.10_plus": "10% أو أكثر",
    "filter.20_plus": "20% أو أكثر",
    "filter.30_plus": "30% أو أكثر",
    "filter.50_plus": "50% أو أكثر",
    "filter.in_stock": "متوفر",
    "filter.out_of_stock": "غير متوفر",
    "filter.preorder": "طلب مسبق",
    "filter.free_shipping": "شحن مجاني",
    "filter.fast_delivery": "توصيل سريع",
    "filter.same_day": "توصيل نفس اليوم",
    "filter.min": "الحد الأدنى",
    "filter.max": "الحد الأقصى",
    "filter.go": "تطبيق",
    "filter.reset": "إعادة تعيين",
    "filter.search_brands": "ابحث عن الماركات...",
    "all_categories": "جميع التصنيفات",
  },
};

export function t(key: string, locale: Locale = "en", params?: Record<string, string | number>): string {
  let text = translations[locale]?.[key] || translations.en[key] || key;
  if (params) {
    Object.entries(params).forEach(([k, v]) => {
      text = text.replace(`{${k}}`, String(v));
    });
  }
  return text;
}
